import type { CvContent, CvExperience, CvEducation } from "@/types/cv"

const PAGE_MARGIN_MM = 18
const SECTION_SPACING = "1.2em"
const BULLET_GAP = "0.4em"
const FONT_SIZE_BODY = 11
const FONT_SIZE_HEADING = 12
const FONT_SIZE_SMALL = 10

function esc(s: string): string {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/#/g, "\\#")
    .replace(/\$/g, "\\$")
    .replace(/</g, "\\<")
    .replace(/>/g, "\\>")
    .replace(/\{/g, "\\{")
    .replace(/\}/g, "\\}")
}

function section(title: string, body: string): string {
  if (!body.trim()) return ""
  return `
#set text(size: ${FONT_SIZE_HEADING}pt, weight: "bold")
[${esc(title)}]
#v(0.4em)
${body}
#v(${SECTION_SPACING})
`
}

function experienceBlock(exp: CvExperience): string {
  const header = [exp.role, exp.company, exp.dates].filter(Boolean).join(" | ")
  const bullets = exp.bullets
    .map((b) => `- ${esc(b)}`)
    .join(`\n#v(${BULLET_GAP})\n`)
  return `
#set text(weight: "bold")
[${esc(header)}]
#v(${BULLET_GAP})
${bullets}
#v(0.6em)
`
}

function educationBlock(edu: CvEducation): string {
  const line = [edu.degree, edu.institution, edu.dates].filter(Boolean).join(" | ")
  return `- ${esc(line)}\n`
}

export function buildTypstDocument(cv: CvContent): string {
  const contactParts = [cv.email, cv.phone].filter(Boolean)
  const contactLine = contactParts.join(" · ")

  const experienceBody = cv.experience.map(experienceBlock).join("")
  const educationBody = cv.education.map(educationBlock).join("")
  const skillsBody = cv.skills.length
    ? cv.skills.map((s) => `- ${esc(s)}`).join(`\n#v(${BULLET_GAP})\n`)
    : ""

  const summaryBlock = cv.summary.trim()
    ? esc(cv.summary)
    : ""

  return `// Generated by CVA — fixed professional CV template (ATS-friendly)
#set page(
  margin: ${PAGE_MARGIN_MM}mm,
  header: none,
  footer: none
)
#set text(size: ${FONT_SIZE_BODY}pt, lang: "en")
#set par(justify: true, leading: 0.65em)

// —— Header ——
#align(center)[
  #set text(size: 14pt, weight: "bold")
  ${esc(cv.name)}
  #v(0.2em)
  #set text(size: ${FONT_SIZE_SMALL}pt)
  ${esc(contactLine)}
]
#v(0.8em)

// —— Summary ——
${summaryBlock ? section("Summary", summaryBlock) : ""}

// —— Experience ——
${experienceBody ? section("Experience", experienceBody) : ""}

// —— Education ——
${educationBody ? section("Education", educationBody) : ""}

// —— Skills ——
${skillsBody ? section("Skills", skillsBody) : ""}
`
}